version: "3.9"

networks:
  atchain-demo:

services:
  orderer.demo.com:
    container_name: orderer.demo.com
    image: hyperledger/fabric-orderer:2.4
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=orderer.demo.com
      - ORDERER_GENERAL_LISTENPORT=18860
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=DemoOrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ../system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../../organization/ordererOrganizations/demo.com/orderers/orderer.demo.com/msp:/var/hyperledger/orderer/msp
      - ../../organization/ordererOrganizations/demo.com/orderers/orderer.demo.com/tls:/var/hyperledger/orderer/tls
    ports:
      - "18860:18860"
    networks:
      - atchain-demo

  peer0.demo.com:
    container_name: peer0.demo.com
    image: hyperledger/fabric-peer:2.4
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=docker_atchain-demo
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_ID=peer0.demo.com
      - CORE_PEER_ADDRESS=peer0.demo.com:18850
      - CORE_PEER_LISTENADDRESS=peer0.demo.com:18850
      - CORE_PEER_CHAINCODEADDRESS=peer0.demo.com:18870
      - CORE_PEER_CHAINCODELISTENADDRESS=peer0.demo.com:18870
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.demo.com:18850 peer1.demo.com:18851 peer2.demo.com:18852
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.demo.com:18850
      - CORE_PEER_LOCALMSPID=DemoMSP
      - CORE_PEER_GATEWAY_ENABLED=true
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_GOSSIP_ENDPOINT=peer0.demo.com:18850
    volumes:
      - /var/run/:/host/var/run/
      - ../../organization/peerOrganizations/demo.com/peers/peer0.demo.com/msp:/etc/hyperledger/fabric/msp
      - ../../organization/peerOrganizations/demo.com/peers/peer0.demo.com/tls:/etc/hyperledger/fabric/tls
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - "18850:18850"
    networks:
      - atchain-demo

  peer1.demo.com:
    container_name: peer1.demo.com
    image: hyperledger/fabric-peer:2.4
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=docker_atchain-demo
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_ID=peer1.demo.com
      - CORE_PEER_ADDRESS=peer1.demo.com:18851
      - CORE_PEER_LISTENADDRESS=peer1.demo.com:18851
      - CORE_PEER_CHAINCODEADDRESS=peer1.demo.com:18871
      - CORE_PEER_CHAINCODELISTENADDRESS=peer1.demo.com:18871
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.demo.com:18850 peer1.demo.com:18851 peer2.demo.com:18852
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.demo.com:18851
      - CORE_PEER_LOCALMSPID=DemoMSP
      - CORE_PEER_GATEWAY_ENABLED=true
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_GOSSIP_ENDPOINT=peer1.demo.com:18851
    volumes:
      - /var/run/:/host/var/run/
      - ../../organization/peerOrganizations/demo.com/peers/peer1.demo.com/msp:/etc/hyperledger/fabric/msp
      - ../../organization/peerOrganizations/demo.com/peers/peer1.demo.com/tls:/etc/hyperledger/fabric/tls
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - "18851:18851"
    networks:
      - atchain-demo

  peer2.demo.com:
    container_name: peer2.demo.com
    image: hyperledger/fabric-peer:2.4
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=docker_atchain-demo
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_ID=peer2.demo.com
      - CORE_PEER_ADDRESS=peer2.demo.com:18852
      - CORE_PEER_LISTENADDRESS=peer2.demo.com:18852
      - CORE_PEER_CHAINCODEADDRESS=peer2.demo.com:18872
      - CORE_PEER_CHAINCODELISTENADDRESS=peer2.demo.com:18872
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.demo.com:18850 peer1.demo.com:18851 peer2.demo.com:18852
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.demo.com:18852
      - CORE_PEER_LOCALMSPID=DemoMSP
      - CORE_PEER_GATEWAY_ENABLED=true
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_GOSSIP_ENDPOINT=peer2.demo.com:18852
    volumes:
      - /var/run/:/host/var/run/
      - ../../organization/peerOrganizations/demo.com/peers/peer2.demo.com/msp:/etc/hyperledger/fabric/msp
      - ../../organization/peerOrganizations/demo.com/peers/peer2.demo.com/tls:/etc/hyperledger/fabric/tls
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - "18852:18852"
    networks:
      - atchain-demo